name: M-Ph-Badin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52666
title: M-Ph-Badin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#ebebeb'
    - '#4c1a21'
    - '#beae8d'
    - '#695453'
  brandStrength: 1
  lightness: 0.0630710874684155
  saturation: 0
  rhythmicContrast: 0
purpose: []
