name: M-Ph-Badin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6993623259477317
title: M-Ph-Badin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6606195371132344
  lightness: 0.0630710874684155
  saturation: 0.23604037426412106
  rhythmicContrast: 0.7862495020963252
purpose: []
